In [62]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [63]:
df=pd.read_csv('Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [64]:
df.shape

(10000, 14)

In [65]:
df.drop(columns=['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

In [66]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [67]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df['Geography']=encoder.fit_transform(df['Geography'])
df['Gender']=encoder.fit_transform(df['Gender'])

In [68]:
df.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [69]:
df=pd.get_dummies(df,columns=['Geography'],drop_first=True)

In [70]:
df.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_1  Geography_2  
0               1        101348.88       1            0            0  
1               1        112542.58       0            0            1  
2               0        113931.57       1            0            0  
3               0         93826.63       0            0            0  
4               1         79084.10       0            0            1

In [71]:
y=df.loc[:,'Exited'].values
y


array([1, 0, 1, ..., 1, 1, 0])

In [72]:
x=df.drop(columns=['Exited'],axis=1).values

In [73]:
x

array([[6.1900000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.0134888e+05,
        0.0000000e+00, 0.0000000e+00],
       [6.0800000e+02, 0.0000000e+00, 4.1000000e+01, ..., 1.1254258e+05,
        0.0000000e+00, 1.0000000e+00],
       [5.0200000e+02, 0.0000000e+00, 4.2000000e+01, ..., 1.1393157e+05,
        0.0000000e+00, 0.0000000e+00],
       ...,
       [7.0900000e+02, 0.0000000e+00, 3.6000000e+01, ..., 4.2085580e+04,
        0.0000000e+00, 0.0000000e+00],
       [7.7200000e+02, 1.0000000e+00, 4.2000000e+01, ..., 9.2888520e+04,
        1.0000000e+00, 0.0000000e+00],
       [7.9200000e+02, 0.0000000e+00, 2.8000000e+01, ..., 3.8190780e+04,
        0.0000000e+00, 0.0000000e+00]])

In [74]:
from sklearn.preprocessing import StandardScaler

In [75]:
scaler=StandardScaler()

In [76]:
x=scaler.fit_transform(x)

In [77]:
x

array([[-0.32622142, -1.09598752,  0.29351742, ...,  0.02188649,
        -0.57873591, -0.57380915],
       [-0.44003595, -1.09598752,  0.19816383, ...,  0.21653375,
        -0.57873591,  1.74273971],
       [-1.53679418, -1.09598752,  0.29351742, ...,  0.2406869 ,
        -0.57873591, -0.57380915],
       ...,
       [ 0.60498839, -1.09598752, -0.27860412, ..., -1.00864308,
        -0.57873591, -0.57380915],
       [ 1.25683526,  0.91241915,  0.29351742, ..., -0.12523071,
         1.72790383, -0.57380915],
       [ 1.46377078, -1.09598752, -1.04143285, ..., -1.07636976,
        -0.57873591, -0.57380915]])

In [78]:
from sklearn.model_selection import train_test_split

In [79]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

In [80]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [81]:
model=Sequential()

In [82]:
model.add(Dense(11,activation='relu',input_dim=x_train.shape[1]))
model.add(Dense(11,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [83]:
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [84]:
his=model.fit(x_train,y_train,batch_size=50,epochs=100,verbose=1,validation_split=0.20)

Epoch 1/100
128/128 [==============================] - 1s 3ms/step - loss: 0.7805 - accuracy: 0.5022 - val_loss: 0.5686 - val_accuracy: 0.7663
Epoch 2/100
128/128 [==============================] - 0s 2ms/step - loss: 0.5280 - accuracy: 0.7902 - val_loss: 0.4879 - val_accuracy: 0.8025
Epoch 3/100
128/128 [==============================] - 0s 2ms/step - loss: 0.4725 - accuracy: 0.8048 - val_loss: 0.4496 - val_accuracy: 0.8106
Epoch 4/100
128/128 [==============================] - 0s 2ms/step - loss: 0.4412 - accuracy: 0.8139 - val_loss: 0.4311 - val_accuracy: 0.8156
Epoch 5/100
128/128 [==============================] - 0s 2ms/step - loss: 0.4248 - accuracy: 0.8175 - val_loss: 0.4209 - val_accuracy: 0.8188
Epoch 6/100
128/128 [==============================] - 0s 2ms/step - loss: 0.4133 - accuracy: 0.8230 - val_loss: 0.4125 - val_accuracy: 0.8225
Epoch 7/100
128/128 [==============================] - 0s 3ms/step - loss: 0.4032 - accuracy: 0.8275 - val_loss: 0.4033 - val_accuracy: 0.8263

In [85]:
y_pred=model.predict(x_test)

63/63 [==============================] - 0s 883us/step


In [87]:
from sklearn.metrics import accuracy_score


In [91]:
acc=accuracy_score(y_test,y_pred)

In [92]:
acc

0.86

In [102]:
from sklearn.metrics import confusion_matrix,classification_report

In [103]:
cm=confusion_matrix(y_test,y_pred)

In [104]:
cm

array([[1529,   66],
       [ 214,  191]])

In [106]:
cr=classification_report(y_test,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1595
           1       0.74      0.47      0.58       405

    accuracy                           0.86      2000
   macro avg       0.81      0.72      0.75      2000
weighted avg       0.85      0.86      0.85      2000

